local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 20.0
   height: 20.0
   resolution: 0.05
   static_map: true
   rolling_window: true
   transform_tolerance: 0.2
